### ISSUE TITLE
Could you share your for files?

### ISSUE THREAD

**Issue by marcthespot0** [antrax2024/gurush#1]
I found your Reddit post and really like your waybar config can you share with me?

**Comment by antrax2024** [comment]
Yes, sure:

You will need modify the files. My waybar config are 3 files: 

# 1. reload.sh
If you modify style.css and config.jsonc files, you can fire this shell script.
```bash
#!/bin/bash

# Envia o sinal SIGUSR1 para a Waybar para recarregar a configuração
WAYBAR_PID=$(pgrep -x waybar)

if [ -z "$WAYBAR_PID" ]; then
  echo "Waybar não está em execução."
else
  kill -9 "$WAYBAR_PID"
  waybar -c ~/dotfiles/waybar-amd-video/config.jsonc -s ~/dotfiles/waybar-amd-video/style.css &
  disown
  echo "ok"
fi

```

# 2. style.css
TIP: Install CaskaydiaCove Nerd Font and Font Awesome 6 (Free and Free Solid)

```css
* {
  font-family: "CaskaydiaCove Nerd Font", "Font Awesome 6 Free", "Font Awesome 6 Free Solid";
  font-weight: bold;
  font-size: 16px;
  color: #dcdfe1;
}

#waybar {
  background-color: rgba(0, 0, 0, 0);
  border: none;
  box-shadow: none;
}

#workspaces,
#window,
#tray {
  background-color: rgba(15, 27, 53, 0.8);
  padding: 4px 6px;
  margin-top: 6px;
  margin-left: 6px;
  margin-right: 6px;
  border-radius: 10px;
  border-width: 0px;
}

#clock {
  background-color: rgba(15, 27, 53, 0.9);
  margin-top: 6px;
  margin-right: 6px;
  padding: 4px 2px;
  border-radius: 0 10px 10px 0;
  border-width: 0px;
}

#cpu {
  background-color: rgba(15, 27, 53, 0.9);
  margin-top: 6px;
  margin-left: 6px;
  padding: 4px 2px;
  border-radius: 10px 0 0 10px;
  border-width: 0px;
}

#network,
#bluetooth,
#temperature,
#pulseaudio,
#memory,
#disk,
#cpu {
  background-color: rgba(15, 27, 53, 0.9);
  margin-top: 6px;
  padding: 4px 2px;
  border-width: 0px;
}

#custpm-temperature.critical,
#pulseaudio.muted {
  color: #FF0000;
  padding-top: 0;
}

#bluetooth:hover,
#network:hover,
#backlight:hover,
#battery:hover,
#pulseaudio:hover,
#custom-temperature:hover,
#memory:hover,
#cpu:hover,
#clock:hover,
#custom-lock:hover,
#custom-reboot:hover,
#custom-power:hover,
#window:hover {
  background-color: rgba(70, 75, 90, 0.9);
}

#workspaces button:hover {
  background-color: rgba(97, 175, 239, 0.2);
  padding: 2px 8px;
  margin: 0 2px;
  border-radius: 10px;
}

#workspaces button.active {
  background-color: #61afef;
  color: #ffffff;
  padding: 2px 8px;
  margin: 0 2px;
  border-radius: 10px;
}

#workspaces button {
  background: transparent;
  border: none;
  color: #888888;
  padding: 2px 8px;
  margin: 0 2px;
  font-weight: bold;
}

#window {
  font-weight: 500;
  font-style: italic;
}

```

# 3. config.jsonc

```json
{
  "layer": "top",
  "position": "top",
  "height": 32,
  "spacing": 0,
  "modules-left": [
    "hyprland/workspaces",
    "hyprland/window"
  ],
  "modules-right": [
    "cpu",
    "temperature",
    "memory",
    "disk",
    "network",
    "bluetooth",
    "pulseaudio",
    "clock",
    "tray"
  ],
  "hyprland/workspaces": {
    "disable-scroll": false,
    "all-outputs": true,
    "format": "{icon}",
    "on-click": "activate",
    "persistent-workspaces": {
      "*": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    "format-icons": {
      "1": "󰣇",
      "2": "󰈹",
      "3": "󰇮",
      "4": "",
      "5": "",
      "default": ""
    }
  },
  "temperature": {
    "hwmon-path": "/sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon1/temp1_input",
    "critical-threshold": 80,
    "format": "<span foreground=\"#FF69B4\"></span> {temperatureC}°C "
  },
  "network": {
    "format-wifi": "<span color='#00FFFF'>󰤨  </span>{essid} ",
    "format-ethernet": "<span color='#7FFF00'>  </span>Wired ",
    "tooltip-format": "<span color='#FF1493'>󰅧  </span>{bandwidthUpBytes}  <span color='#00BFFF'> 󰅢 </span>{bandwidthDownBytes}",
    "format-linked": "<span color='#FFA500'>󱘖 </span>{ifname} (No IP) ",
    "format-disconnected": "<span color='#FF4040'>  </span>Disconnected ",
    "format-alt": "<span color='#00FFFF'>󰤨  </span>{signalStrength}% ",
    "interval": 1
  },
  "pulseaudio": {
    "format": "<span color='#00FF7F'>{icon}</span>{volume}% ",
    "format-muted": "<span color='#FF4040'>󰖁</span>0% ",
    "format-icons": {
      "headphone": "<span color='#BF00FF'> </span>",
      "hands-free": "<span color='#BF00FF'> </span>",
      "headset": "<span color='#BF00FF'> </span>",
      "phone": "<span color='#00FFFF'></span>",
      "portable": "<span color='#00FFFF'></span>",
      "car": "<span color='#FFA500'> </span>",
      "default": [
        "<span color='#808080'></span>",
        "<span color='#FFFF66'></span>",
        "<span color='#00FF7F'> </span>"
      ]
    },
    "on-click-right": "pavucontrol-qt -t 3",
    "on-click": "pactl -- set-sink-mute 0 toggle",
    "tooltip": true,
    "tooltip-format": "volume: {volume}%"
  },
  "disk": {
    "interval": 10,
    "format": "<span color=\"#00CED1\"></span> {used}/{free} ",
    "path": "/",
    "unit": "GB"
  },
  "memory": {
    "format": "<span color='#8A2BE2'>  </span>{used:0.1f}G/{total:0.1f}G ",
    "tooltip": true,
    "tooltip-format": "ram: {used:0.2f}G/{total:0.2f}G",
    "interval": 1
  },
  "cpu": {
    "format": "<span color='#FF9F0A'>  </span>{usage}% ",
    "tooltip": true
  },
  "clock": {
    "interval": 1,
    "timezone": "America/Fortaleza",
    "format": "<span color='#BF00FF'>  </span>{:%d/%m/%Y %H:%M:%S} ",
    "tooltip": true,
    "tooltip-format": "{:%d/%m/%Y %H:%M:%S}"
  },
  "tray": {
    "icon-size": 17,
    "spacing": 6
  },
  "bluetooth": {
    "format": "<span color='#00BFFF'> </span>{status} ",
    "format-connected": "<span color='#00BFFF'> </span>{device_alias} ",
    "format-connected-battery": "<span color='#00BFFF'> </span>{device_alias}{device_battery_percentage}% ",
    "tooltip-format": "{controller_alias}\t{controller_address}\n\n{num_connections} connected",
    "tooltip-format-connected": "{controller_alias}\t{controller_address}\n\n{num_connections} connected\n\n{device_enumerate}",
    "tooltip-format-enumerate-connected": "{device_alias}\t{device_address}",
    "tooltip-format-enumerate-connected-battery": "{device_alias}\t{device_address}\t{device_battery_percentage}%"
  }
}

```

Good luck !
